export const reviewsData = [
  {
    text: '“Vestibulum auctor mi sit amet mauris ultrices, vel tincidunt purus vulputate. Duis vitae leo a justo condimentum imperdiet vel in sapien. In hac habitasse platea dictumst. Nulla facilisi. Aliquam erat volutpat.”',
    author: 'Alice Johnson, Tech Innovations',
    img: 'team-member.jpg',
  },
  {
    text: '“Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum. Duis mollis, est non commodo luctus, nisi erat ”',
    author: 'Lesale Christoper, Pinterest',
    img: 'team-member.jpg',
  },
  {
    text: '“Suspendisse potenti. Cras eget nisi vel elit scelerisque posuere. Curabitur sit amet augue non nunc viverra scelerisque. Integer ullamcorper cursus lacus vel consequat. Sed eu orci auctor, malesuada odio ut, malesuada libero.”',
    author: 'David  Anderson, Data Systems Inc.',
    img: 'team-member.jpg',
  },
  {
    text: '“Phasellus vel quam vel est accumsan cursus. In hac habitasse platea dictumst. Suspendisse ut justo a urna facilisis scelerisque nec non neque. Nulla facilisi. Sed tincidunt risus nec purus euismod, at volutpat odio vulputate.”',
    author: 'Emily Rodriguez,Digital Dynamics',
    img: 'team-member.jpg',
  },
  {
    text: '“Quisque at velit ut justo imperdiet varius in eu orci. Nulla facilisi. Sed fringilla nunc eu arcu facilisis, vitae placerat nisl efficitur. Sed vel sapien quis justo ullamcorper vehicula. Morbi euismod dapibus justo, nec fermentum justo mattis ut.”',
    author: 'George Thompson, Innovate Tech',
    img: 'team-member.jpg',
  },
  {
    text: '“Integer vel urna eu ex feugiat euismod. Fusce vestibulum risus vel metus laoreet, vel eleifend purus suscipit. Maecenas aliquam metus eu metus luctus, in interdum justo auctor. Sed vel leo nec arcu vestibulum luctus nec eu ante.”',
    author: 'Olivia Lewis, Tech Trends',
    img: 'team-member.jpg',
  },
];

export const projectsData = [
  {
    id: 'prj1',
    categories: ['apps', 'web'],
    title: 'Neque Porro Quisquam',
    date: 2018,
    industry: 'Finance',
    client: 'Creative Agency',
    timeline: '6 months',
    website: {
      name: 'example1.com',
      link: 'https://example1.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-1.png',
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj2',
    categories: ['web', 'icons'],
    title: 'Neque Porro Quisquam',
    date: 2019,
    industry: 'Sport',
    client: 'Sports Company',
    timeline: '3 months',
    website: {
      name: 'example2.com',
      link: 'https://example2.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-2.png',
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj3',
    categories: ['web', 'apps'],
    title: 'Neque Porro Quisquam',
    date: 2021,
    industry: 'Travel',
    client: 'Travel Agency',
    timeline: '4 months',
    website: {
      name: 'example3.com',
      link: 'https://example3.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-3.png',
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj4',
    categories: ['web'],
    title: 'Neque Porro Quisquam',
    date: 2020,
    industry: 'Live Media',
    client: 'Media Company',
    timeline: '5 months',
    website: {
      name: 'example4.com',
      link: 'https://example4.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-4.png',
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj5',
    categories: ['icons', 'apps'],
    title: 'Neque Porro Quisquam',
    date: 2023,
    industry: 'Automotive',
    client: 'Automotive Tech',
    timeline: '8 months',
    website: {
      name: 'example5.com',
      link: 'https://example5.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-5.png',
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj6',
    categories: ['apps'],
    title: 'Neque Porro Quisquam',
    date: 2024,
    industry: 'Live Media',
    client: 'Media Production',
    timeline: '7 months',
    website: {
      name: 'example6.com',
      link: 'https://example6.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-6.png',
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj7',
    categories: ['web', 'icons'],
    title: 'Project title 7',
    date: 2023,
    industry: 'Tourism',
    client: 'Tourism Board',
    timeline: '5 months',
    website: {
      name: 'example7.com',
      link: 'https://example7.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj8',
    categories: ['apps'],
    title: 'Project title 8',
    date: 2024,
    industry: 'Ecommerce',
    client: 'Ecommerce Store',
    timeline: '6 months',
    website: {
      name: 'example8.com',
      link: 'https://example8.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj9',
    categories: ['icons'],
    title: 'Project title 9',
    date: 2024,
    industry: 'Healthcare',
    client: 'Health Tech',
    timeline: '9 months',
    website: {
      name: 'example9.com',
      link: 'https://example9.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj10',
    categories: ['apps', 'web'],
    title: 'Project title 10',
    date: 2024,
    industry: 'Security System',
    client: 'Security Solutions',
    timeline: '10 months',
    website: {
      name: 'example10.com',
      link: 'https://example10.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj11',
    categories: ['web', 'apps'],
    title: 'Project title 11',
    date: 2024,
    industry: 'Healthcare',
    client: 'Healthcare Solutions',
    timeline: '8 months',
    website: {
      name: 'example11.com',
      link: 'https://example11.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj12',
    categories: ['web', 'icons'],
    title: 'Project title 12',
    date: 2024,
    industry: 'Ecommerce',
    client: 'Online Retail',
    timeline: '6 months',
    website: {
      name: 'example12.com',
      link: 'https://example12.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj13',
    categories: ['icons'],
    title: 'Project title 13',
    date: 2023,
    industry: 'Ecommerce',
    client: 'Ecommerce Solutions',
    timeline: '7 months',
    website: {
      name: 'example13.com',
      link: 'https://example13.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj14',
    categories: ['web'],
    title: 'Project title 14',
    date: 2020,
    industry: 'Live Media',
    client: 'Media Streaming',
    timeline: '4 months',
    website: {
      name: 'example14.com',
      link: 'https://example14.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj15',
    categories: ['icons'],
    title: 'Project title 15',
    date: 2021,
    industry: 'Tourism',
    client: 'Tourism App',
    timeline: '5 months',
    website: {
      name: 'example15.com',
      link: 'https://example15.com',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
];
